epochs: 200
init_lr: 1e-2
weight_decay: 0.0 #4e-5
num_workers: 8
batch_size: 6
step_size:
  - 100
seed: 2021
opt_lv: "O0"
save_epoch: 1000
step_down_rate: 0.1
num_classes: 10
load: false
dataset_dir: "~/datasets/camvid480_360/" #"/groups/gcc50527/ninnart/datasets/imagenet256"
load_dir: "entropy/0_8973.pth"

distributed: true
# Total number of GPU
world_size: 4
backend: "nccl"
# Trying with arbitary tcp not work!
init_method: "tcp://127.0.0.1:2021"